### PR TITLE
feat: switch to Atlas for DDL

### LINKED ISSUE #147: Add a README for database migration
Currently, there is no explanation for database migration.

We need to place a README at `Global-Indexer/internal/database/dialer/cockroachdb/migration`, to explain how to initiate a migration with goose.

### PR DESCRIPTION
**Pull request by HenryQW**
1. Since Atlas does not support multiple schemas with gorm+crdb, I have moved all schemas to `public`.
2. Production workflow needs to be set up (not the scope of this PR, and ops is out of my league).
3. See `internal/database/dialer/cockroachdb/README.md` for more information.

A second CRDB container is needed as a temporary DB for Atlas to perform its magic.

Close #147

### CODE REVIEW

**Comment by HenryQW** [comment]
also it's worth paying attention to https://github.com/RSS3-Network/Node/issues/208

**Comment by polebug** [comment]
Got a dilemma：

When creating a table, it needs to generate the `"id" bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0)`

But gorm's tag doesn't cover this requirement, its `autoIncrement `, `autoIncrement ` don't work (docs: https://gorm.io/docs/models.html#Fields-Tags)

**Comment by Candinya** [comment]
add a reminder: GORM's tag cannot specify the name of Composite Primary Key, some database requires (manual) reconstruction

**Comment by Candinya** [comment]
## Table name (schema) change

- bridge
  - `bridge.events` -> `bridge_events`
  - `bridge.transactions` -> `bridge_transactions`
- node
  - `node.events` -> `node_events`
  - `node.min_tokens_to_stake_snapshots` -> `node_min_tokens_to_stake_snapshots`
  - `node.count_snapshots` -> `node_count_snapshots`
  - `node.operator_profit_snapshots` -> `node_operator_profit_snapshots`
- stake
  - `stake.chips` -> `stake_chips`
  - `stake.events` -> `stake_events`
  - `stake.transactions` -> `stake_transactions`
  - `stake.count_snapshots` -> `stake_count_snapshots`
  - `stake.profit_snapshots` -> `stake_profit_snapshots`

## Table field change

- node_info: `local` -> `location`
- epoch: `total_reward_items` -> `total_reward_nodes`
- epoch_item:
  - `tax_amounts` -> `tax_collected`
  - `request_counts` -> `request_count`

**Comment by Candinya** [comment]
Change table commands: (Refer to https://www.cockroachlabs.com/docs/stable/alter-table )

Change table name:

```sql
ALTER TABLE ... RENAME TO ...
```

Change table schema:

```sql
ALTER TABLE ... SET SCHEMA ...
```

Change column name:

```sql
ALTER TABLE ... ALTER COLUMN ...
```

**Comment by Candinya** [comment]
keep manually maintained SQL + more tests

**Pull request closed without merging**
